# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('P', 'Parent'), ('S', 'Student')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to='financeapp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funds', models.DecimalField(decimal_places=2, max_digits=6)),
                ('account', models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to='financeapp.Account')),
            ],
        ),
        migrations.AddField(
            model_name='parentaccount',
            name='student_accounts',
            field=models.ManyToManyField(to='financeapp.StudentAccount'),
        ),
    ]
