# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0002_auto_20161122_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funds', models.DecimalField(decimal_places=2, max_digits=6)),
                ('account', models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to='financeapp.Account')),
            ],
        ),
    ]
